# Generated by Django 3.2.16 on 2023-03-07 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path_template',
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_types',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
    ]
