# Generated by Django 3.2.16 on 2023-03-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_email'),
        ('documents', '0002_auto_20230307_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='institution',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='institutions.institution',
                verbose_name='Institution',
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
