# Generated by Django 3.2.16 on 2023-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20230309_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='acronym',
            field=models.TextField(default='', verbose_name='Acronym'),
        ),
    ]
