# Generated by Django 3.2.16 on 2023-03-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('documents', '0004_document_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commission',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='commissions.commission',
                verbose_name='Commission',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='process_type',
            field=models.CharField(
                choices=[
                    ('CHARTER_ASSOCIATION', 'Charter for Association'),
                    (
                        'CHARTER_ASSOCIATION_INSTITUTION',
                        'Charter for Association Institution',
                    ),
                    ('CHARTER_PROJECT_COMMISSION', 'Charter for Project Commission'),
                    ('DOCUMENT_ASSOCIATION', 'Document for Association'),
                    ('DOCUMENT_USER', 'Document for User'),
                    ('DOCUMENT_PROJECT', 'Document for Project'),
                    ('DOCUMENT_PROJECT_REVIEW', 'Document for Project Review'),
                ],
                default='DOCUMENT_PROCESSING',
                max_length=32,
                verbose_name='Status',
            ),
        ),
    ]
