# Generated by Django 3.2.18 on 2023-03-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20230310_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={
                'permissions': [
                    (
                        'delete_document_any_institution',
                        'Can delete documents linked to any institution.',
                    )
                ],
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
