# Generated by Django 3.2.18 on 2023-03-22 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0031_auto_20230309_1018'),
        ('projects', '0002_alter_project_options'),
        ('documents', '0006_alter_document_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentAssociationUser',
            new_name='DocumentUpload',
        ),
    ]
