# Generated by Django 3.2.16 on 2023-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_path_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='status',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='document_upload_status',
            field=models.CharField(
                choices=[
                    ('DOCUMENT_REJECTED', 'Document Rejected'),
                    ('DOCUMENT_PROCESSING', 'Document Processing'),
                    ('DOCUMENT_VALIDATED', 'Document Validated'),
                ],
                default='DOCUMENT_PROCESSING',
                max_length=32,
                verbose_name='Document Upload Status',
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='process_type',
            field=models.CharField(
                choices=[
                    ('CHARTER_ASSOCIATION', 'Charter for Association'),
                    (
                        'CHARTER_ASSOCIATION_INSTITUTION',
                        'Charter for Association Institution',
                    ),
                    ('CHARTER_PROJECT_COMMISSION', 'Charter for Project Commission'),
                    ('DOCUMENT_ASSOCIATION', 'Document for Association'),
                    ('DOCUMENT_USER', 'Document for User'),
                    ('DOCUMENT_PROJECT', 'Document for Project'),
                    ('DOCUMENT_PROJECT_REVIEW', 'Document for Project Review'),
                ],
                default='DOCUMENT_PROCESSING',
                max_length=32,
                verbose_name='Document Status',
            ),
        ),
    ]
