# Generated by Django 3.2.16 on 2023-03-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20230327_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentupload',
            options={
                'permissions': [
                    (
                        'add_documentupload_all',
                        'Can add a link from any document to any project or anu association.',
                    ),
                    (
                        'delete_documentupload_all',
                        'Can remove a link from a document to any project or any association.',
                    ),
                    (
                        'view_documentupload_all',
                        'Can view all documents linked to any project or any association.',
                    ),
                ],
                'verbose_name': 'Document from association or user',
                'verbose_name_plural': 'Documents from associations or users',
            },
        ),
    ]
