# Generated by Django 3.2.16 on 2023-03-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_documentupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={
                'permissions': [
                    (
                        'add_document_any_commission',
                        'Can add documents linked to any commission.',
                    ),
                    (
                        'add_document_any_institution',
                        'Can add documents linked to any institution.',
                    ),
                    (
                        'delete_document_any_commission',
                        'Can delete documents linked to any commission.',
                    ),
                    (
                        'delete_document_any_institution',
                        'Can delete documents linked to any institution.',
                    ),
                ],
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
