# Generated by Django 3.2.16 on 2023-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0011_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_required_in_process',
            field=models.BooleanField(default=False, verbose_name='Is required'),
        ),
        migrations.AlterField(
            model_name='document',
            name='process_type',
            field=models.CharField(
                choices=[
                    ('CHARTER_ASSOCIATION', 'Charter for Association'),
                    (
                        'CHARTER_ASSOCIATION_INSTITUTION',
                        'Charter for Association Institution',
                    ),
                    ('CHARTER_PROJECT_COMMISSION', 'Charter for Project Commission'),
                    ('DOCUMENT_ASSOCIATION', 'Document for Association'),
                    ('DOCUMENT_USER', 'Document for User'),
                    ('DOCUMENT_PROJECT', 'Document for Project'),
                    ('DOCUMENT_PROJECT_REVIEW', 'Document for Project Review'),
                ],
                default='DOCUMENT_PROJECT',
                max_length=32,
                verbose_name='Document Status',
            ),
        ),
    ]
