# Generated by Django 3.2.16 on 2023-04-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0012_auto_20230412_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={
                'permissions': [
                    (
                        'add_document_any_commission',
                        'Can add documents linked to any commission.',
                    ),
                    (
                        'add_document_any_institution',
                        'Can add documents linked to any institution.',
                    ),
                    (
                        'change_document_any_commission',
                        'Can change documents linked to any commission.',
                    ),
                    (
                        'change_document_any_institution',
                        'Can change documents linked to any institution.',
                    ),
                    (
                        'delete_document_any_commission',
                        'Can delete documents linked to any commission.',
                    ),
                    (
                        'delete_document_any_institution',
                        'Can delete documents linked to any institution.',
                    ),
                ],
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='is_required_in_process',
            field=models.BooleanField(
                default=False, verbose_name='Is required in process'
            ),
        ),
    ]
