# Generated by Django 3.2.16 on 2023-04-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0013_auto_20230412_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Name'),
        ),
    ]
