# Generated by Django 3.2.18 on 2023-04-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0014_documentupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contact',
            field=models.TextField(default='', verbose_name='Contact address'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='process_type',
            field=models.CharField(
                choices=[
                    ('CHARTER_ASSOCIATION', 'Charter for Association'),
                    (
                        'CHARTER_ASSOCIATION_INSTITUTION',
                        'Charter for Association Institution',
                    ),
                    ('CHARTER_PROJECT_COMMISSION', 'Charter for Project Commission'),
                    ('DOCUMENT_ASSOCIATION', 'Document for Association'),
                    ('DOCUMENT_USER', 'Document for User'),
                    ('DOCUMENT_PROJECT', 'Document for Project'),
                    ('DOCUMENT_PROJECT_REVIEW', 'Document for Project Review'),
                    ('NO_PROCESS', 'Document not linked to a process'),
                ],
                default='NO_PROCESS',
                max_length=32,
                verbose_name='Document Status',
            ),
        ),
    ]
