# Generated by Django 3.2.19 on 2023-05-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0003_auto_20230531_0942'),
        ('documents', '0016_auto_20230503_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='commission',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='commissions.fund',
                verbose_name='Fund',
            ),
        ),
    ]
