# Generated by Django 3.2.16 on 2023-06-09 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0039_association_charter_date'),
        ('projects', '0029_auto_20230609_1541'),
        ('documents', '0019_auto_20230601_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='association',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='associations.association',
                verbose_name='Association',
            ),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='document',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='documents.document',
                verbose_name='Document',
            ),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='project',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.project',
                verbose_name='Project',
            ),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
