# Generated by Django 3.2.16 on 2023-06-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0020_auto_20230609_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='is_validated_by_admin',
            field=models.BooleanField(
                default=False, verbose_name='Is validated by admin'
            ),
        ),
    ]
