# Generated by Django 3.2.16 on 2023-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0021_documentupload_is_validated_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='is_validated_by_admin',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='validated_date',
            field=models.DateField(null=True, verbose_name='Validated date'),
        ),
    ]
