# Generated by Django 3.2.16 on 2023-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0022_auto_20230616_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='days_before_expiration',
            field=models.DurationField(
                null=True, verbose_name='Days before document expiration'
            ),
        ),
    ]
