# Generated by Django 3.2.16 on 2023-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0023_alter_document_days_before_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiration_day',
            field=models.CharField(
                max_length=5,
                null=True,
                verbose_name='Document expiration day of the year in %m-%d format',
            ),
        ),
    ]
