# Generated by Django 3.2.20 on 2023-08-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0024_document_expiration_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='comment',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
