# Generated by Django 3.2.20 on 2023-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0026_alter_documentupload_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='edition_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Edition date'),
        ),
    ]
