# Generated by Django 4.2.9 on 2024-01-22 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0027_document_edition_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentupload',
            options={
                'permissions': [
                    ('add_documentupload_all', 'Can add a link from any document to any project or any association.'),
                    (
                        'delete_documentupload_all',
                        'Can remove a link from a document to any project or any association.',
                    ),
                    ('view_documentupload_all', 'Can view all documents linked to any project or any association.'),
                ],
                'verbose_name': 'Document from association or user',
                'verbose_name_plural': 'Documents from associations or users',
            },
        ),
    ]
