# Generated by Django 4.2.16 on 2025-10-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_remove_institution_email'),
        ('commissions', '0009_fund_attribution_template_path_and_more'),
        ('documents', '0029_alter_document_days_before_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='acronym',
            field=models.TextField(verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='document',
            name='days_before_expiration',
            field=models.DurationField(blank=True, null=True, verbose_name='Days before document expiration'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiration_day',
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name='Document expiration day of the year in %m-%d format'
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='fund',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='commissions.fund',
                verbose_name='Fund',
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='institution',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='institutions.institution',
                verbose_name='Institution',
            ),
        ),
    ]
