# Generated by Django 4.2.16 on 2025-10-03 12:20
import datetime

from django.db import migrations, models


def duration_to_int(apps, schema_editor):
    Model = apps.get_model("documents", "Document")
    for obj in Model.objects.all():
        if obj.days_before_expiration is not None:
            obj.days_before_expiration_int = int(obj.days_before_expiration.total_seconds())
            obj.save(update_fields=["days_before_expiration_int"])


def int_to_duration(apps, schema_editor):
    Model = apps.get_model("documents", "Document")
    for obj in Model.objects.all():
        if obj.days_before_expiration_int is not None:
            obj.days_before_expiration = datetime.timedelta(seconds=obj.days_before_expiration_int)
            obj.save(update_fields=["days_before_expiration"])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_alter_document_acronym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="days_before_expiration_int",
            field=models.IntegerField(null=True, blank=True, verbose_name='Days before document expiration'),
        ),
        migrations.RunPython(duration_to_int, reverse_code=int_to_duration),
        migrations.RemoveField(
            model_name="document",
            name="days_before_expiration"
        ),
        migrations.RenameField(
            model_name='document',
            old_name='days_before_expiration_int',
            new_name='days_before_expiration',
        ),
    ]
