# Generated by Django 4.2.16 on 2025-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_alter_document_days_before_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
