# Generated by Django 4.2.16 on 2026-04-07 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_project_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0032_alter_documentupload_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.project',
                verbose_name='Project',
            ),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
