# Generated by Django 4.2.16 on 2025-09-29 07:10

import django.core.validators
from django.db import migrations, models


def migrate_is_multiple_to_max_uploads(apps, schema_editor):
    Document = apps.get_model("documents", "Document")

    Document.objects.filter(is_multiple=True).update(max_uploads=10)
    Document.objects.filter(is_multiple=False).update(max_uploads=1)


def reverse_max_uploads(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    # Si max_uploads > 1, on considère que c'était un is_multiple=True
    Document.objects.filter(max_uploads__gt=1).update(is_multiple=True)
    Document.objects.filter(max_uploads=1).update(is_multiple=False)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_alter_documentupload_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='max_uploads',
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum copies number allowed'
            ),
        ),
        migrations.RunPython(migrate_is_multiple_to_max_uploads, reverse_code=reverse_max_uploads),
        migrations.RemoveField(
            model_name='document',
            name='is_multiple',
        ),
    ]
