# Generated by Django 4.2.16 on 2026-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_remove_document_is_multiple_document_max_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Contact address'),
        ),
    ]
