stages:
  - build
  - scan
  - release

include:
  - project: "docker/template"
    file: "docker-scan.gitlab-ci.yml"

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/dnum/campulse-backend:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/dnum/campulse-backend:latest
  EXTRA_ARGS: ""
