stages:
  - test

services:
  - postgres

variables:
  POSTGRES_DB: plana_test
  POSTGRES_USER: plana
  POSTGRES_PASSWORD: plana

#unittest:
#  stage: test
#  tags:
#    - python3.9
#  script:
#    - pip3 install tox
#    - tox
#  coverage: '/^TOTAL.*\s+(\d+\%)$/'
