---
services:
  backend:
    build: .
    env_file: .env
      # - LOG_PATH=/app/logs/app.log
    volumes:
      - static:/app/assets
      - ./logs:/app/logs
  #  depends_on:
  #    postgres:
  #      condition: service_healthy
# networks:
#   plana-net:
#     ipv4_address: 172.16.1.4

volumes:
  static:
