services:
  plana-backend:
    build: .
    env_file: .env
    volumes:
      - plana-static:/var/www/plana-backend
      - ./logs:/var/log/plana-backend
    network_mode: host

volumes:
  plana-static:
