version: "3.9"
services:
  postgres:
    image: postgres:12
    container_name: plana-db
    environment:
      - POSTGRES_DB=plana
      - POSTGRES_USER=plana
      - POSTGRES_PASSWORD=plana
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  api:
    container_name: plana-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    hostname: back
    volumes:
      - ./plana/settings:/app/plana/settings
      - ./plana/keys:/app/plana/keys
    ports:
      - "8080:8080"
    env_file:
      - ./docker/.env.dev
    links:
      - postgres
    depends_on:
      - postgres

  maildev:
    image: maildev/maildev:2.0.5
    container_name: plana-maildev
    ports:
      - 1080:1080
      - 1025:1025
    restart: unless-stopped
