version: "3.9"
services:
  postgres:
    container_name: plana-db
    hostname: bdd
    build:
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./docker/db/.env.dev
    restart: always
    volumes:
      - plana-db:/var/lib/postgresql/data

  api:
    container_name: plana-api
    hostname: back
    build:
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./docker/api/.env.dev
    depends_on:
      - postgres

  maildev:
    image: maildev/maildev:2.0.5
    container_name: plana-maildev
    ports:
      - 1080:1080
      - 1025:1025
    restart: unless-stopped

volumes:
  plana-db:
    driver: local
