[tool.black]
line-length = 88
skip-string-normalization = true
target-version = ['py39']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | plana\/settings
    | plana\/apps\/associations\/migrations
    | plana\/apps\/commissions\/migrations
    | plana\/apps\/contents\/migrations
    | plana\/apps\/documents\/migrations
    | plana\/apps\/groups\/migrations
    | plana\/apps\/institutions\/migrations
    | plana\/apps\/projects\/migrations
    | plana\/apps\/users\/migrations
    | fabfile
    | _build
    | buck-out
    | build
    | dist
  )/
  | manage.py
  | tox.ini
  | .coveragerc
                     # the root of the project
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.poetry]
name = "plana"
version = "0.2.20230720"
description = ""
authors = ["DIP - Université de Strasbourg <dnum-dip@unistra.fr>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
django = "<4.0"
django-allauth = "^0.51.0"
django-allauth-cas = "^1.0.0"
# django-allauth-cas = { git = "https://github.com/thejoeejoee/django-allauth-cas", branch = "master" }
django-cleanup = "^6.0.0"
django-cors-headers = "^3.13.0"
django-extensions = "^3.2.0"
django-storages = {extras = ["boto3"], version = "^1.13.2"}
django-summernote = "<0.9"
django-thumbnails = "^0.7.0"
djangorestframework = "^3.14.0"
djangorestframework-camel-case = "^1.3.0"
djangorestframework-simplejwt = "^5.2.0"
dj-rest-auth = "^2.2.0"
drf-spectacular = "^0.24.0"
britney = "^0.5.1"
pillow = "^9.5.0" # needed because ANTIALIAS is deprecated in v10.
psycopg2-binary = "2.8.6"
pyrage = "^1.0.3"
urllib3 = ">=1.26,<2" # needed to avoid dependency problems when updating boto3 and botocore
weasyprint = "^58.1"
zxcvbn = "^4.4.28"
num2words = "^0.5.12"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
coverage = "^6.5.0"
django-debug-toolbar = "^3.7.0"
pre-commit = "^2.20.0"
pycodestyle = "^2.9.0"
pylint = "^2.15.0"
pylint-django = "^2.5.0"
safety = "^2.3.5"
sentry-sdk = "^1.9.0"
tox = "^3.26.0"

[tool.poetry.group.prod.dependencies]
chaussette-backport = "1.3.1"
sentry-sdk = "^1.9.0"
waitress = "2.1.2"

[tool.poetry.group.preprod.dependencies]
chaussette-backport = "^1.3.1"
sentry-sdk = "^1.9.0"
waitress = "2.1.2"

[tool.poetry.group.test.dependencies]
chaussette-backport = "^1.3.1"
sentry-sdk = "^1.9.0"
waitress = "2.1.2"
