sonar.projectKey=plana-back
sonar.qualitygate.wait=true
sonar.exclusions=**/test_*,docs/*,fabfile/*,**/settings/**,**/migrations/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.coverage.xmlReportPaths=coverage.xml

sonar.exclusions=**/test_*,docs/*,fabfile/*,**/migrations/*
sonar.test.inclusions=**/test_*
sonar.coverage.exclusions=**/test_*,docs/*,fabfile/*,**/migrations/*
sonar.cpd.exclusions=**/test_*,docs/*,fabfile/*,**/migrations/*
