# Generated by Django 3.2.16 on 2022-10-27 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0003_auto_20221027_1609"),
        ("users", "0004_rename_is_cas_user_user_is_cas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="associationusers",
            options={
                "verbose_name": "Association",
                "verbose_name_plural": "Associations",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": [],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="associationusers",
            name="association",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="associations.association",
                verbose_name="Association",
            ),
        ),
        migrations.AlterField(
            model_name="associationusers",
            name="has_office_status",
            field=models.BooleanField(default=False, verbose_name="Has office status"),
        ),
        migrations.AlterField(
            model_name="associationusers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="association_members",
            field=models.ManyToManyField(
                through="users.AssociationUsers",
                to="associations.Association",
                verbose_name="Associations",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_cas",
            field=models.BooleanField(default=False, verbose_name="Is CAS account"),
        ),
    ]
