# Generated by Django 3.2.16 on 2022-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221027_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False, verbose_name='Is validated by administrator'),
        ),
    ]
