# Generated by Django 3.2.16 on 2022-11-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_cas',
        ),
    ]
