# Generated by Django 3.2.16 on 2022-11-24 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20221121_1117"),
    ]

    operations = [
        migrations.CreateModel(
            name="GDPRConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=256, verbose_name="GDPR Consent title"),
                ),
            ],
            options={
                "verbose_name": "GDPR Consent",
                "verbose_name_plural": "GDPR Consents",
            },
        ),
        migrations.CreateModel(
            name="GDPRConsentUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_consented",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Consent date"
                    ),
                ),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gdprconsent",
                        verbose_name="GDPR Consent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "GDPR Consent User",
                "verbose_name_plural": "GDPR Consents Users",
            },
        ),
    ]
