# Generated by Django 3.2.16 on 2022-11-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consents", "__first__"),
        ("users", "0013_gdprconsent_gdprconsentusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gdprconsentusers",
            name="consent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="consents.gdprconsent",
                verbose_name="GDPR Consent",
            ),
        ),
        migrations.DeleteModel(
            name="GDPRConsent",
        ),
    ]
