# Generated by Django 3.2.16 on 2022-12-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_consents_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='association_members',
            new_name='associations',
        ),
    ]
