# Generated by Django 3.2.16 on 2023-01-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_association_members_user_associations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationusers',
            name='has_office_status',
        ),
        migrations.AddField(
            model_name='associationusers',
            name='can_be_president',
            field=models.BooleanField(default=False, verbose_name='Can be president'),
        ),
    ]
