# Generated by Django 3.2.16 on 2023-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0020_usergroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='Groups'),
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
    ]
