# Generated by Django 3.2.16 on 2023-01-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('users', '0022_groupusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupusers',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
    ]
