# Generated by Django 3.2.16 on 2023-01-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institutions', '0001_initial'),
        ('users', '0023_alter_groupusers_institution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupUsers',
            new_name='GroupInstitutionUsers',
        ),
    ]
