# Generated by Django 3.2.16 on 2023-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0025_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups_institutions',
            field=models.ManyToManyField(related_name='group_institution_set', through='users.GroupInstitutionUsers', to='auth.Group', verbose_name='Groups'),
        ),
    ]
