# Generated by Django 3.2.16 on 2023-01-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_groups_institutions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinstitutionusers',
            options={'verbose_name': 'User Institution Groups', 'verbose_name_plural': 'Users Institution Groups'},
        ),
    ]
