# Generated by Django 3.2.16 on 2023-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_groupinstitutionusers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinstitutionusers',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is staff'),
        ),
    ]
