# Generated by Django 3.2.16 on 2023-02-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_groupinstitutionusers_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationusers',
            options={'permissions': [('change_associationusers_any_institution', 'Can change associations for all users.'), ('delete_associationusers_any_institution', 'Can delete associations for all users.'), ('view_associationusers_anyone', 'Can view all associations for a user.')], 'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.AlterModelOptions(
            name='gdprconsentusers',
            options={'permissions': [], 'verbose_name': 'GDPR Consent User', 'verbose_name_plural': 'GDPR Consents Users'},
        ),
        migrations.AlterModelOptions(
            name='groupinstitutionusers',
            options={'permissions': [('view_groupinstitutionusers_anyone', 'Can view all groups for a user.')], 'verbose_name': 'User Institution Groups', 'verbose_name_plural': 'Users Institution Groups'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='groupinstitutionusers',
            name='is_staff',
        ),
    ]
