# Generated by Django 3.2.16 on 2023-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationusers',
            name='role_name',
        ),
        migrations.AddField(
            model_name='associationusers',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='Is secretary'),
        ),
        migrations.AddField(
            model_name='associationusers',
            name='is_treasurer',
            field=models.BooleanField(default=False, verbose_name='Is treasurer'),
        ),
        migrations.AddField(
            model_name='associationusers',
            name='is_validated_by_admin',
            field=models.BooleanField(
                default=False, verbose_name='Is validated by admin'
            ),
        ),
    ]
