# Generated by Django 3.2.16 on 2023-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_last_change_date',
            field=models.DateField(null=True, verbose_name='Password last change date'),
        ),
    ]
