# Generated by Django 3.2.16 on 2023-03-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commissions', '0001_initial'),
        ('institutions', '0002_institution_email'),
        ('users', '0033_user_password_last_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInstitutionCommissionUsers',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'commission',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='commissions.commission',
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='auth.group'
                    ),
                ),
                (
                    'institution',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='institutions.institution',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Institution Commission Groups',
                'verbose_name_plural': 'Users Institution Commission Groups',
                'permissions': [
                    (
                        'view_groupinstitutioncommissionusers_anyone',
                        'Can view all groups for a user.',
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name='associationusers',
            name='can_submit_projects',
            field=models.BooleanField(default=True, verbose_name='Can submit projects'),
        ),
        migrations.DeleteModel(
            name='GroupInstitutionUsers',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups_institutions',
            field=models.ManyToManyField(
                related_name='group_institution_set',
                through='users.GroupInstitutionCommissionUsers',
                to='auth.Group',
                verbose_name='Groups',
            ),
        ),
    ]
