# Generated by Django 3.2.16 on 2023-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20230307_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationusers',
            name='can_be_president_from',
            field=models.DateTimeField(null=True, verbose_name='Can be president from'),
        ),
        migrations.AddField(
            model_name='associationusers',
            name='can_be_president_to',
            field=models.DateTimeField(null=True, verbose_name='Can be president to'),
        ),
        migrations.AddField(
            model_name='associationusers',
            name='is_vice_president',
            field=models.BooleanField(default=False, verbose_name='Is vice president'),
        ),
    ]
