# Generated by Django 3.2.16 on 2023-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20230309_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationusers',
            name='can_be_president_from',
            field=models.DateField(null=True, verbose_name='Can be president from'),
        ),
        migrations.AlterField(
            model_name='associationusers',
            name='can_be_president_to',
            field=models.DateField(null=True, verbose_name='Can be president to'),
        ),
    ]
