# Generated by Django 3.2.16 on 2023-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20230309_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationusers',
            name='can_submit_projects',
        ),
        migrations.AddField(
            model_name='user',
            name='can_submit_projects',
            field=models.BooleanField(default=True, verbose_name='Can submit projects'),
        ),
    ]
