# Generated by Django 3.2.16 on 2023-03-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20230310_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinstitutioncommissionusers',
            options={
                'permissions': [
                    (
                        'add_groupinstitutioncommissionusers_any_group',
                        'Can add restricted groups to a user.',
                    ),
                    (
                        'view_groupinstitutioncommissionusers_anyone',
                        'Can view all groups for a user.',
                    ),
                ],
                'verbose_name': 'User Institution Commission Groups',
                'verbose_name_plural': 'Users Institution Commission Groups',
            },
        ),
    ]
