# Generated by Django 3.2.16 on 2023-03-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_groupinstitutioncommissionusers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinstitutioncommissionusers',
            options={
                'permissions': [
                    (
                        'add_groupinstitutioncommissionusers_any_group',
                        'Can add restricted groups to a user.',
                    ),
                    (
                        'delete_groupinstitutioncommissionusers_any_group',
                        'Can delete restricted groups to a user.',
                    ),
                    (
                        'view_groupinstitutioncommissionusers_any_group',
                        'Can view all groups for a user.',
                    ),
                ],
                'verbose_name': 'User Institution Commission Groups',
                'verbose_name_plural': 'Users Institution Commission Groups',
            },
        ),
    ]
