# Generated by Django 3.2.16 on 2023-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20230330_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationuser',
            name='can_be_president',
        ),
        migrations.AddField(
            model_name='associationuser',
            name='can_be_president_permanent',
            field=models.BooleanField(
                default=False, verbose_name='Can be president without a timeframe'
            ),
        ),
    ]
