# Generated by Django 3.2.16 on 2023-04-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20230331_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationuser',
            name='can_be_president_permanent',
        ),
    ]
