# Generated by Django 3.2.16 on 2023-04-04 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0043_remove_associationuser_can_be_president_permanent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consents_given',
        ),
        migrations.DeleteModel(
            name='GDPRConsentUsers',
        ),
    ]
