# Generated by Django 3.2.16 on 2023-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0044_auto_20230404_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
        ),
    ]
