# Generated by Django 3.2.16 on 2023-05-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0045_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=128, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='', max_length=32, verbose_name='Zipcode'),
        ),
    ]
