# Generated by Django 3.2.16 on 2023-05-26 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0047_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                default='',
                max_length=32,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Wrong phone number format.',
                        regex='^[+]?[(]?[0-9]{3}[)]?[-\\s.]?[0-9]{3}[-\\s.]?[0-9]{4,6}$',
                    )
                ],
                verbose_name='Phone',
            ),
        ),
    ]
