# Generated by Django 3.2.16 on 2023-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0048_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                default='', max_length=32, null=True, verbose_name='Phone'
            ),
        ),
    ]
