# Generated by Django 3.2.19 on 2023-05-31 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('institutions', '0003_remove_institution_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commissions', '0003_auto_20230531_0942'),
        ('users', '0049_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupInstitutionCommissionUser',
            new_name='GroupInstitutionFundUser',
        ),
        migrations.AlterModelOptions(
            name='groupinstitutionfunduser',
            options={
                'permissions': [
                    (
                        'add_groupinstitutioncommissionuser_any_group',
                        'Can add restricted groups to a user.',
                    ),
                    (
                        'delete_groupinstitutioncommissionuser_any_group',
                        'Can delete restricted groups to a user.',
                    ),
                    (
                        'view_groupinstitutioncommissionuser_any_group',
                        'Can view all groups for a user.',
                    ),
                ],
                'verbose_name': 'User Institution Fund Groups',
                'verbose_name_plural': 'Users Institution Fund Groups',
            },
        ),
    ]
