# Generated by Django 3.2.19 on 2023-05-31 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0050_auto_20230531_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinstitutionfunduser',
            options={
                'permissions': [
                    (
                        'add_groupinstitutionfunduser_any_group',
                        'Can add restricted groups to a user.',
                    ),
                    (
                        'delete_groupinstitutionfunduser_any_group',
                        'Can delete restricted groups to a user.',
                    ),
                    (
                        'view_groupinstitutionfunduser_any_group',
                        'Can view all groups for a user.',
                    ),
                ],
                'verbose_name': 'User Institution Fund Groups',
                'verbose_name_plural': 'Users Institution Fund Groups',
            },
        ),
        migrations.RenameField(
            model_name='groupinstitutionfunduser',
            old_name='commission',
            new_name='fund',
        ),
    ]
