# Generated by Django 3.2.19 on 2023-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0051_auto_20230531_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups_institutions_commissions',
        ),
        migrations.AddField(
            model_name='user',
            name='groups_institutions_funds',
            field=models.ManyToManyField(
                related_name='group_institution_fund_set',
                through='users.GroupInstitutionFundUser',
                to='auth.Group',
                verbose_name='Groups',
            ),
        ),
    ]
