# Generated by Django 3.2.16 on 2023-06-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0008_commission_name'),
        ('institutions', '0003_remove_institution_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0052_auto_20230601_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinstitutionfunduser',
            name='fund',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='commissions.fund',
            ),
        ),
        migrations.AlterField(
            model_name='groupinstitutionfunduser',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='auth.group'
            ),
        ),
        migrations.AlterField(
            model_name='groupinstitutionfunduser',
            name='institution',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='institutions.institution',
            ),
        ),
    ]
