# Generated by Django 3.2.16 on 2023-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0053_auto_20230609_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Is student'),
        ),
    ]
