# Generated by Django 4.2.9 on 2024-01-22 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0054_user_is_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationuser',
            options={
                'permissions': [
                    ('change_associationuser_any_institution', 'Can change associations for all users.'),
                    ('delete_associationuser_any_institution', 'Can delete associations for all users.'),
                    ('view_associationuser_anyone', 'Can view all associations for a user.'),
                ],
                'verbose_name': 'User Association',
                'verbose_name_plural': 'Users Associations',
            },
        ),
    ]
