# Generated by Django 4.2.19 on 2025-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='associationuser',
            constraint=models.UniqueConstraint(fields=('user', 'association'), name='unique_association_user'),
        ),
        migrations.AddConstraint(
            model_name='groupinstitutionfunduser',
            constraint=models.UniqueConstraint(
                fields=('user', 'group', 'institution', 'fund'), name='unique_group_institution_fund_user'
            ),
        ),
    ]
