# Generated by Django 4.2.16 on 2025-10-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_remove_institution_email'),
        ('commissions', '0009_fund_attribution_template_path_and_more'),
        ('users', '0057_associationuser_unique_association_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinstitutionfunduser',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.fund'),
        ),
        migrations.AlterField(
            model_name='groupinstitutionfunduser',
            name='institution',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'
            ),
        ),
    ]
