# Generated by Django 3.2.16 on 2023-01-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('acronym', models.CharField(max_length=30, verbose_name='Acronym')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='InstitutionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='institutions', to='institutions.institution', verbose_name='Institution')),
            ],
            options={
                'verbose_name': 'Institution component',
                'verbose_name_plural': 'Institution components',
            },
        ),
    ]
