# Generated by Django 3.2.16 on 2023-02-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(
                default='plan-a.noreply@unistra.fr',
                max_length=254,
                verbose_name='Email',
            ),
            preserve_default=False,
        ),
    ]
