# Generated by Django 4.2.6 on 2023-10-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('documents', '0027_document_edition_date'),
        ('users', '0054_user_is_student'),
        ('projects', '0041_alter_projectcomment_options_and_more'),
        ('associations', '0043_alter_association_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'action_title',
                    models.CharField(
                        choices=[
                            ('USER_LOGGED', 'A user is logged in'),
                            ('USER_REGISTERED', 'A user is registered'),
                            ('USER_VALIDATED', 'A user is validated'),
                            ('ASSOCIATION_CHANGED', 'An association is changed'),
                            ('ASSOCIATION_CHARTER_CHANGED', 'An association charter is changed'),
                            ('ASSOCIATION_USER_VALIDATED', 'A link between an association and a user is validated'),
                            ('ASSOCIATION_USER_CHANGED', 'A link between an association and a user is changed'),
                            (
                                'ASSOCIATION_USER_DELEGATION_CHANGED',
                                'A delegation between an association and a user is changed',
                            ),
                            ('GROUP_INSTITUTION_FUND_USER_CHANGED', 'A link between group and user is changed'),
                            ('DOCUMENT_UPLOAD_CHANGED', 'A document upload is changed'),
                            ('PROJECT_VALIDATED', 'A project is validated'),
                        ],
                        max_length=64,
                        verbose_name='Action title',
                    ),
                ),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                (
                    'action_user_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='action_user_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User who did action',
                    ),
                ),
                (
                    'association_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='associations.association',
                        verbose_name='Association affected by change',
                    ),
                ),
                (
                    'association_user_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='users.associationuser',
                        verbose_name='Link between association and user affected by change',
                    ),
                ),
                (
                    'document_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='documents.document',
                        verbose_name='Document affected by change',
                    ),
                ),
                (
                    'group_institution_fund_user_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='users.groupinstitutionfunduser',
                        verbose_name='Link between group and user affected by change',
                    ),
                ),
                (
                    'project_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='projects.project',
                        verbose_name='Project affected by change',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='user_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User affected by change',
                    ),
                ),
            ],
        ),
    ]
