# Generated by Django 4.2.6 on 2023-10-09 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='action_user_id',
            new_name='action_user',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='association_id',
            new_name='association',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='association_user_id',
            new_name='association_user',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='group_institution_fund_user_id',
            new_name='group_institution_fund_user',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
    ]
