# Generated by Django 4.2.6 on 2023-10-09 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0027_document_edition_date'),
        ('history', '0002_rename_action_user_id_history_action_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='document',
        ),
        migrations.AddField(
            model_name='history',
            name='document_upload',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='documents.documentupload',
                verbose_name='Document affected by change',
            ),
        ),
    ]
