# Generated by Django 4.2.6 on 2023-10-09 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('history', '0004_alter_history_association_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
    ]
