# Generated by Django 3.2.16 on 2023-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=128, unique=True, verbose_name='Code'),
                ),
                (
                    'label',
                    models.CharField(max_length=128, unique=True, verbose_name='Label'),
                ),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
