# Generated by Django 3.2.16 on 2023-04-05 06:28

from django.conf import settings
from django.db import migrations


def change_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site, _ = Site.objects.get_or_create(pk=settings.SITE_ID)
    site.name = 'Opaline'
    site.domain = 'plana-pprd.app.unistra.fr'
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contents', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(change_site_name),
    ]
