# Generated by Django 3.2.16 on 2023-04-05 06:28

from django.db import migrations


def change_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get(name='example.com')
    site.name = 'Opaline'
    site.domain = 'plana-pprd.app.unistra.fr'
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_site_name),
    ]
