# Generated by Django 3.2.16 on 2023-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contents', '0002_auto_20230405_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='footer',
            field=models.TextField(default='', verbose_name='Footer'),
        ),
        migrations.AddField(
            model_name='content',
            name='header',
            field=models.TextField(default='', verbose_name='Header'),
        ),
    ]
