# Generated by Django 3.2.19 on 2023-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contents', '0003_auto_20230425_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sidebar',
            field=models.TextField(default='', verbose_name='Sidebar'),
        ),
    ]
