# Generated by Django 3.2.16 on 2023-07-06 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contents', '0004_content_sidebar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='sidebar',
            new_name='aside',
        ),
    ]
