# Generated by Django 4.2.7 on 2023-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contents', '0009_alter_content_aside_alter_content_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='aside',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Sidebar'),
        ),
        migrations.AlterField(
            model_name='content',
            name='footer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='content',
            name='header',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Title'),
        ),
    ]
