# Generated by Django 4.2.9 on 2024-01-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contents', '0010_alter_content_aside_alter_content_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_editable',
            field=models.BooleanField(default=False, verbose_name='Is editable'),
        ),
    ]
