# Generated by Django 4.2.16 on 2025-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='aside',
            field=models.TextField(blank=True, default='', verbose_name='Sidebar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='footer',
            field=models.TextField(blank=True, default='', verbose_name='Footer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='header',
            field=models.TextField(blank=True, default='', verbose_name='Header'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
