# Generated by Django 3.2.16 on 2023-03-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0030_association_can_submit_projects'),
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                (
                    'planned_start_date',
                    models.DateTimeField(null=True, verbose_name='Start date'),
                ),
                (
                    'planned_end_date',
                    models.DateTimeField(null=True, verbose_name='End date'),
                ),
                ('location', models.TextField(default='', verbose_name='Location')),
                (
                    'budget_previous_edition',
                    models.IntegerField(
                        default=0, verbose_name='Budget on previous edition'
                    ),
                ),
                (
                    'target_audience',
                    models.TextField(default='', verbose_name='Target audience'),
                ),
                (
                    'type_target_audience',
                    models.CharField(
                        default='',
                        max_length=64,
                        verbose_name='Type of people in target audience (student, employees, ...)',
                    ),
                ),
                (
                    'amount_target_audience',
                    models.IntegerField(
                        default=0, verbose_name='Amount of people in target audience'
                    ),
                ),
                (
                    'amount_students_target_audience',
                    models.IntegerField(
                        default=0, verbose_name='Amount of students in target audience'
                    ),
                ),
                (
                    'ticket_price',
                    models.IntegerField(
                        default=0, verbose_name='Amount of money asked for each person'
                    ),
                ),
                (
                    'individual_cost',
                    models.IntegerField(
                        default=0, verbose_name='Amount of money needed by person'
                    ),
                ),
                ('goals', models.TextField(default='', verbose_name='Goals')),
                ('summary', models.TextField(default='', verbose_name='Summary')),
                (
                    'planned_activities',
                    models.TextField(default='', verbose_name='Planned activites'),
                ),
                (
                    'prevention_safety',
                    models.TextField(
                        default='', verbose_name='Planned prevention and safety actions'
                    ),
                ),
                (
                    'marketing_campaign',
                    models.TextField(default='', verbose_name='Marketing campaign'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PROJECT_DRAFT', 'Project Draft'),
                            ('PROJECT_REJECTED', 'Project Rejected'),
                            ('PROJECT_PROCESSING', 'Project Processing'),
                            ('PROJECT_VALIDATED', 'Project Validated'),
                            ('PROJECT_REVIEW_DRAFT', 'Project Review Draft'),
                            ('PROJECT_REVIEW_REJECTED', 'Project Review Rejected'),
                            ('PROJECT_REVIEW_PROCESSING', 'Project Review Processing'),
                            ('PROJECT_REVIEW_VALIDATED', 'Project Review Validated'),
                        ],
                        default='PROJECT_DRAFT',
                        max_length=32,
                        verbose_name='Status',
                    ),
                ),
                (
                    'creation_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Creation date'
                    ),
                ),
                (
                    'edition_date',
                    models.DateTimeField(auto_now=True, verbose_name='Edition date'),
                ),
                ('outcome', models.IntegerField(default=0, verbose_name='Outcome')),
                ('income', models.IntegerField(default=0, verbose_name='Income')),
                (
                    'real_start_date',
                    models.DateTimeField(null=True, verbose_name='Start date'),
                ),
                (
                    'real_end_date',
                    models.DateTimeField(null=True, verbose_name='End date'),
                ),
                (
                    'organizer_name',
                    models.CharField(
                        default='', max_length=256, verbose_name='Organizer name'
                    ),
                ),
                (
                    'organizer_phone',
                    models.CharField(
                        default='', max_length=32, verbose_name='Organizer phone'
                    ),
                ),
                (
                    'organizer_email',
                    models.CharField(
                        default='', max_length=256, verbose_name='Organizer email'
                    ),
                ),
                (
                    'review',
                    models.TextField(
                        default='',
                        verbose_name='Review (amount of students, partnerships, ...)',
                    ),
                ),
                (
                    'impact_students',
                    models.TextField(default='', verbose_name='Impact on students'),
                ),
                (
                    'description',
                    models.TextField(
                        default='',
                        verbose_name='Description (activities done, changes from planning, ...)',
                    ),
                ),
                (
                    'difficulties',
                    models.TextField(default='', verbose_name='Difficulties'),
                ),
                (
                    'improvements',
                    models.TextField(default='', verbose_name='Improvements'),
                ),
                (
                    'association',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='associations.association',
                        verbose_name='Association',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectCommissionDate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_first_edition',
                    models.BooleanField(default=True, verbose_name='Is first edition'),
                ),
                (
                    'amount_asked_previous_edition',
                    models.IntegerField(
                        default=0, verbose_name='Amount asked on previous edition'
                    ),
                ),
                (
                    'amount_earned_previous_edition',
                    models.IntegerField(
                        default=0, verbose_name='Amount earned on previous edition'
                    ),
                ),
                (
                    'amount_asked',
                    models.IntegerField(default=0, verbose_name='Amount asked'),
                ),
                (
                    'amount_earned',
                    models.IntegerField(default=0, verbose_name='Amount earned'),
                ),
                (
                    'commission_date',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='commissions.commissiondate',
                        verbose_name='Commission Date',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='projects.project',
                        verbose_name='Project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project commission date',
                'verbose_name_plural': 'Projects commissions dates',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='projects.category',
                        verbose_name='Project Category',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='projects.project',
                        verbose_name='Project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project category',
                'verbose_name_plural': 'Projects categories',
            },
        ),
    ]
