# Generated by Django 3.2.18 on 2023-03-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={
                'permissions': [
                    (
                        'change_project_restricted_fields',
                        'Can update projects restricted fields.',
                    )
                ],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
