# Generated by Django 3.2.16 on 2023-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(
                choices=[
                    ('PROJECT_DRAFT', 'Project Draft'),
                    ('PROJECT_REJECTED', 'Project Rejected'),
                    ('PROJECT_PROCESSING', 'Project Processing'),
                    ('PROJECT_VALIDATED', 'Project Validated'),
                    ('PROJECT_REVIEW_DRAFT', 'Project Review Draft'),
                    ('PROJECT_REVIEW_REJECTED', 'Project Review Rejected'),
                    ('PROJECT_REVIEW_PROCESSING', 'Project Review Processing'),
                    ('PROJECT_REVIEW_VALIDATED', 'Project Review Validated'),
                ],
                default='PROJECT_DRAFT',
                max_length=32,
                verbose_name='Project Status',
            ),
        ),
    ]
