# Generated by Django 3.2.16 on 2023-03-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230327_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={
                'permissions': [
                    (
                        'change_project_basic_fields',
                        'Can update projects basic fields.',
                    ),
                    (
                        'change_project_restricted_fields',
                        'Can update projects restricted fields (status, ...).',
                    ),
                    ('view_project_all', 'Can view all projects.'),
                ],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcommissiondate',
            options={
                'permissions': [
                    (
                        'change_projectcommissiondate_basic_fields',
                        'Can update basic fields between a project and a commission date.',
                    ),
                    (
                        'change_projectcommissiondate_restricted_fields',
                        'Can update restricted fields (amount earned, ...) between a project and a commission date.',
                    ),
                    (
                        'view_projectcommissiondate_all',
                        'Can view all commission dates linked to a project.',
                    ),
                ],
                'verbose_name': 'Project commission date',
                'verbose_name_plural': 'Projects commissions dates',
            },
        ),
    ]
