# Generated by Django 3.2.16 on 2023-04-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0005_auto_20230328_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rejection_comment',
            field=models.TextField(default='', verbose_name='Rejection comment'),
        ),
    ]
