# Generated by Django 3.2.16 on 2023-04-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_project_rejection_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rejection_comment',
        ),
        migrations.AddField(
            model_name='projectcommissiondate',
            name='is_validated_by_admin',
            field=models.BooleanField(
                default=False, verbose_name='Is validated by admin'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(
                choices=[
                    ('PROJECT_DRAFT', 'Project Draft'),
                    ('PROJECT_REJECTED', 'Project Rejected'),
                    ('PROJECT_PROCESSING', 'Project Processing'),
                    ('PROJECT_VALIDATED', 'Project Validated'),
                    ('PROJECT_REVIEW_CANCELLED', 'Project Review Cancelled'),
                    ('PROJECT_REVIEW_DRAFT', 'Project Review Draft'),
                    ('PROJECT_REVIEW_REJECTED', 'Project Review Rejected'),
                    ('PROJECT_REVIEW_PROCESSING', 'Project Review Processing'),
                    ('PROJECT_REVIEW_VALIDATED', 'Project Review Validated'),
                ],
                default='PROJECT_DRAFT',
                max_length=32,
                verbose_name='Project Status',
            ),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Text')),
                (
                    'creation_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Creation date'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='projects',
                        to='projects.project',
                        verbose_name='Project',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='users',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project comment',
                'verbose_name_plural': 'Projects comments',
                'permissions': [
                    (
                        'view_projectcomment_all',
                        'Can view all comments linked to all projects.',
                    )
                ],
            },
        ),
    ]
