# Generated by Django 3.2.16 on 2023-04-14 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0007_auto_20230411_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={
                'permissions': [
                    ('add_project_association', 'Can add a project as an association.'),
                    ('add_project_user', 'Can add a project as a user.'),
                    (
                        'change_project_basic_fields',
                        'Can update projects basic fields.',
                    ),
                    (
                        'change_project_restricted_fields',
                        'Can update projects restricted fields (status, ...).',
                    ),
                    ('view_project_all', 'Can view all projects.'),
                ],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
