# Generated by Django 3.2.16 on 2023-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0008_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='amount_students_target_audience',
            new_name='amount_students_audience',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amount_target_audience',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type_target_audience',
        ),
        migrations.AddField(
            model_name='project',
            name='amount_all_audience',
            field=models.IntegerField(
                default=0, verbose_name='Amount of all people in target audience'
            ),
        ),
    ]
