# Generated by Django 3.2.16 on 2023-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0009_auto_20230417_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_all_audience',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Amount of all people in target audience'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_students_audience',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Amount of students in target audience'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_previous_edition',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Budget on previous edition'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='income',
            field=models.PositiveIntegerField(default=0, verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='project',
            name='individual_cost',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Amount of money needed by person'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcome',
            field=models.PositiveIntegerField(default=0, verbose_name='Outcome'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ticket_price',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Amount of money asked for each person'
            ),
        ),
        migrations.AlterField(
            model_name='projectcommissiondate',
            name='amount_asked',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount asked'),
        ),
        migrations.AlterField(
            model_name='projectcommissiondate',
            name='amount_asked_previous_edition',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Amount asked on previous edition'
            ),
        ),
        migrations.AlterField(
            model_name='projectcommissiondate',
            name='amount_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount earned'),
        ),
        migrations.AlterField(
            model_name='projectcommissiondate',
            name='amount_earned_previous_edition',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Amount earned on previous edition'
            ),
        ),
    ]
