# Generated by Django 3.2.16 on 2023-05-03 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0014_auto_20230428_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={
                'permissions': [
                    ('add_project_association', 'Can add a project as an association.'),
                    ('add_project_user', 'Can add a project as a user.'),
                    (
                        'change_project_as_bearer',
                        'Can update project fields filled by bearer (student).',
                    ),
                    (
                        'change_project_as_validator',
                        'Can update project fields filled by validator (manager).',
                    ),
                    (
                        'view_project_any_commission',
                        'Can view all projects for a commission.',
                    ),
                    (
                        'view_project_any_institution',
                        'Can view all projects for an institution.',
                    ),
                ],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={
                'permissions': [
                    (
                        'view_projectcategory_any_commission',
                        'Can view all categories linked to all projects for a commission.',
                    ),
                    (
                        'view_projectcategory_any_institution',
                        'Can view all categories linked to all projects for an institution.',
                    ),
                ],
                'verbose_name': 'Project category',
                'verbose_name_plural': 'Projects categories',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={
                'permissions': [
                    (
                        'view_projectcomment_any_commission',
                        'Can view all comments linked to all projects for a commission.',
                    ),
                    (
                        'view_projectcomment_any_institution',
                        'Can view all comments linked to all projects for an institution.',
                    ),
                ],
                'verbose_name': 'Project comment',
                'verbose_name_plural': 'Projects comments',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcommissiondate',
            options={
                'permissions': [
                    (
                        'change_projectcommissiondate_as_bearer',
                        'Can update bearer fields (amount asked) between a project and a commission date.',
                    ),
                    (
                        'change_projectcommissiondate_as_validator',
                        'Can update validator fields (amount earned) between a project and a commission date.',
                    ),
                    (
                        'view_projectcommissiondate_any_commission',
                        'Can view all commission dates linked to all projects for a commission.',
                    ),
                    (
                        'view_projectcommissiondate_any_institution',
                        'Can view all commission dates linked to all projects for an institution.',
                    ),
                ],
                'verbose_name': 'Project commission date',
                'verbose_name_plural': 'Projects commissions dates',
            },
        ),
    ]
