# Generated by Django 3.2.16 on 2023-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0015_auto_20230503_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='planned_location',
            field=models.TextField(default='', verbose_name='Planned location'),
        ),
        migrations.AddField(
            model_name='project',
            name='real_location',
            field=models.TextField(default='', verbose_name='Real location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_end_date',
            field=models.DateTimeField(null=True, verbose_name='Planned end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_start_date',
            field=models.DateTimeField(null=True, verbose_name='Planned start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='real_end_date',
            field=models.DateTimeField(null=True, verbose_name='Real end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='real_start_date',
            field=models.DateTimeField(null=True, verbose_name='Real start date'),
        ),
    ]
