# Generated by Django 3.2.16 on 2023-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0017_alter_project_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organizer_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organizer_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organizer_phone',
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='edition_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Edition date'),
        ),
    ]
