# Generated by Django 3.2.16 on 2023-05-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0018_auto_20230522_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='projects',
                to='projects.project',
                verbose_name='Project',
            ),
        ),
    ]
