# Generated by Django 3.2.19 on 2023-06-02 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0004_rename_commissiondate_commission'),
        ('projects', '0022_alter_projectcommissiondate_commission_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCommissionDate',
            new_name='ProjectCommissionFund',
        ),
    ]
