# Generated by Django 3.2.19 on 2023-06-05 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'projects',
            '0024_rename_commission_date_projectcommissionfund_commission_fund',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcommissionfund',
            options={
                'permissions': [
                    (
                        'change_projectcommissionfund_as_bearer',
                        'Can update bearer fields (amount asked) between a project and a commission fund.',
                    ),
                    (
                        'change_projectcommissionfund_as_validator',
                        'Can update validator fields (amount earned) between a project and a commission fund.',
                    ),
                    (
                        'view_projectcommissionfund_any_commission',
                        'Can view all commission funds linked to all projects for a commission.',
                    ),
                    (
                        'view_projectcommissionfund_any_institution',
                        'Can view all commission funds linked to all projects for an institution.',
                    ),
                ],
                'verbose_name': 'Project commission fund',
                'verbose_name_plural': 'Projects commissions funds',
            },
        ),
    ]
