# Generated by Django 3.2.19 on 2023-06-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0006_auto_20230605_1000'),
        ('projects', '0025_alter_projectcommissionfund_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcommissionfund',
            name='commission_fund',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='commissions.commissionfund',
                verbose_name='Commission Fund',
            ),
        ),
    ]
