# Generated by Django 3.2.16 on 2023-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0026_alter_projectcommissionfund_commission_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='other_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='other_first_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='other_last_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='other_phone',
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(
                default='', max_length=150, null=True, verbose_name='Contact email'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_first_name',
            field=models.CharField(
                default='', max_length=150, null=True, verbose_name='Contact first name'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_last_name',
            field=models.CharField(
                default='', max_length=150, null=True, verbose_name='Contact last name'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(
                default='', max_length=32, null=True, verbose_name='Contact phone'
            ),
        ),
    ]
