# Generated by Django 3.2.16 on 2023-06-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0052_auto_20230601_1015'),
        ('projects', '0027_auto_20230605_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_last_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='project',
            name='association_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='users.associationuser',
                verbose_name='Association User',
            ),
        ),
    ]
