# Generated by Django 3.2.16 on 2023-06-09 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0028_auto_20230609_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to='projects.category',
                verbose_name='Project Category',
            ),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='projects',
                to='projects.project',
                verbose_name='Project',
            ),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
