# Generated by Django 3.2.16 on 2023-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0029_auto_20230609_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manual_identifier',
            field=models.CharField(
                max_length=8, null=True, unique=True, verbose_name='Manual identifier'
            ),
        ),
    ]
