# Generated by Django 3.2.16 on 2023-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0030_project_manual_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sustainable_development',
            field=models.TextField(default='', verbose_name='Sustainable development'),
        ),
    ]
