# Generated by Django 3.2.16 on 2023-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0034_alter_projectcommissionfund_amount_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcommissionfund',
            name='amount_earned',
            field=models.PositiveIntegerField(
                default=None, null=True, verbose_name='Amount earned'
            ),
        ),
    ]
