# Generated by Django 3.2.16 on 2023-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0035_alter_projectcommissionfund_amount_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(
                choices=[
                    ('PROJECT_DRAFT', 'Project Draft'),
                    ('PROJECT_DRAFT_PROCESSED', 'Project Draft Processed'),
                    ('PROJECT_PROCESSING', 'Project Processing'),
                    ('PROJECT_REJECTED', 'Project Rejected'),
                    ('PROJECT_VALIDATED', 'Project Validated'),
                    ('PROJECT_REVIEW_DRAFT', 'Project Review Draft'),
                    ('PROJECT_REVIEW_PROCESSING', 'Project Review Processing'),
                    ('PROJECT_REVIEW_VALIDATED', 'Project Review Validated'),
                    ('PROJECT_CANCELED', 'Project Canceled'),
                ],
                default='PROJECT_DRAFT',
                max_length=32,
                verbose_name='Project Status',
            ),
        ),
    ]
