# Generated by Django 3.2.20 on 2023-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0038_project_partner_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='processing_date',
            field=models.DateTimeField(null=True, verbose_name='Processing date'),
        ),
    ]
