# Generated by Django 4.2.5 on 2023-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0040_project_student_ticket_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomment',
            options={
                'permissions': [
                    (
                        'view_projectcomment_any_fund',
                        'Can view all comments linked to all projects for a fund.',
                    ),
                    (
                        'view_projectcomment_any_institution',
                        'Can view all comments linked to all projects for an institution.',
                    ),
                    (
                        'view_projectcomment_not_visible',
                        'Can view all comments even if they are restricted.',
                    ),
                ],
                'verbose_name': 'Project comment',
                'verbose_name_plural': 'Projects comments',
            },
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is visible'),
        ),
    ]
