# Generated by Django 4.2.7 on 2023-11-14 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0041_alter_projectcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_all_audience',
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Amount of all people in target audience',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_previous_edition',
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Budget on previous edition',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='individual_cost',
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Amount of money needed by person',
            ),
        ),
    ]
