# Generated by Django 4.2.9 on 2024-01-24 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0043_alter_project_budget_previous_edition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={
                'permissions': [
                    (
                        'view_projectcategory_any_fund',
                        'Can view all categories linked to all projects for a commission.',
                    ),
                    (
                        'view_projectcategory_any_institution',
                        'Can view all categories linked to all projects for an institution.',
                    ),
                ],
                'verbose_name': 'Project category',
                'verbose_name_plural': 'Projects categories',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcommissionfund',
            options={
                'permissions': [
                    (
                        'change_projectcommissionfund_as_bearer',
                        'Can update bearer fields (amount asked) between a project and a commission fund.',
                    ),
                    (
                        'change_projectcommissionfund_as_validator',
                        'Can update validator fields (amount earned) between a project and a commission fund.',
                    ),
                    (
                        'view_projectcommissionfund_any_fund',
                        'Can view all commission funds linked to all projects for a commission.',
                    ),
                    (
                        'view_projectcommissionfund_any_institution',
                        'Can view all commission funds linked to all projects for an institution.',
                    ),
                ],
                'verbose_name': 'Project commission fund',
                'verbose_name_plural': 'Projects commissions funds',
            },
        ),
    ]
