# Generated by Django 4.2.16 on 2024-10-16 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_associationuser_options'),
        ('projects', '0044_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='association_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='users.associationuser',
                verbose_name='Association User',
            ),
        ),
    ]
