# Generated by Django 4.2.16 on 2025-03-04 13:51

import django.core.validators
from django.db import migrations
import plana.apps.projects.models.project_commission_fund
import plana.storages


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_projectcommissionfund_last_notification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcommissionfund',
            name='last_notification_file',
            field=plana.storages.DynamicStorageFileField(
                blank=True,
                upload_to=plana.apps.projects.models.project_commission_fund.get_file_path,
                validators=[django.core.validators.FileExtensionValidator(['pdf'])],
                verbose_name='Last notification file',
            ),
        ),
    ]
