# Generated by Django 4.2.19 on 2025-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_alter_projectcommissionfund_last_notification_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(through='projects.ProjectCategory', to='projects.category'),
        ),
    ]
