# Generated by Django 4.2.16 on 2026-06-29 12:58

from django.db import migrations, models
from django.db.models.functions import Length, Substr


def truncate_project_names(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Project.objects.annotate(
        name_len=Length('name')
    ).filter(
        name_len__gt=100
    ).update(
        name=Substr('name', 1, 100)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_project_categories'),
    ]

    operations = [
        # Truncate project names first
        migrations.RunPython(truncate_project_names, reverse_code=migrations.RunPython.noop),

        # Then apply the new max_length restriction on db field
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
