# Generated by Django 4.2.19 on 2026-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is enabled'),
        ),
    ]
