# Generated by Django 4.2.19 on 2026-08-25 13:59

from django.db import migrations


def reset_draft_projects_categories(apps, schema_editor):
    ProjectCategory = apps.get_model('projects', 'ProjectCategory')
    ProjectCategory.objects.filter(
        project__project_status__in=["PROJECT_DRAFT", "PROJECT_DRAFT_PROCESSED"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_category_is_enabled'),
    ]

    operations = [
        # CLeaning remaining draft projects to apply new ProjectCategory rules
        migrations.RunPython(reset_draft_projects_categories, reverse_code=migrations.RunPython.noop),
    ]
