########################
# Groups & Permissions #
########################

PERMISSIONS_GROUPS = {
    "MANAGER_GENERAL": [
        "add_association",
        "add_association_any_institution",
        "change_association",
        "change_association_any_institution",
        "change_association_any_president",
        "change_association_all_fields",
        "delete_association",
        "delete_association_any_institution",
        "view_association_not_enabled",
        "view_association_not_public",
        "add_user",
        "change_user",
        "change_user_anyone",
        "delete_user",
        "view_user",
        "view_user_anyone",
        "add_associationusers",
        "add_associationusers_any_institution",
        "change_associationusers",
        "change_associationusers_president",
        "change_associationusers_any_institution",
        "delete_associationusers",
        "delete_associationusers_any_institution",
        "view_associationusers",
        "add_groupinstitutionusers",
        "add_groupinstitutionusers_any_institution",
        "delete_groupinstitutionusers",
        "delete_groupinstitutionusers_any_institution",
        "view_groupinstitutionusers",
    ],
    "MANAGER_INSTITUTION": [
        "add_association",
        "change_association",
        "change_association_any_president",
        "change_association_all_fields",
        "delete_association",
        "view_association_not_enabled",
        "view_association_not_public",
        "add_user",
        "change_user",
        "change_user_anyone",
        "delete_user",
        "view_user",
        "view_user_anyone",
        "add_associationusers",
        "change_associationusers",
        "change_associationusers_president",
        "delete_associationusers",
        "view_associationusers",
        "add_groupinstitutionusers",
        "delete_groupinstitutionusers",
        "view_groupinstitutionusers",
    ],
    "MANAGER_MISC": [
        "add_association",
        "change_association",
        "change_association_any_president",
        "change_association_all_fields",
        "delete_association",
        "view_association_not_enabled",
        "view_association_not_public",
        "add_user",
        "change_user",
        "change_user_anyone",
        "delete_user",
        "view_user",
        "view_user_anyone",
        "add_associationusers",
        "change_associationusers",
        "change_associationusers_president",
        "delete_associationusers",
        "view_associationusers",
        "add_groupinstitutionusers",
        "delete_groupinstitutionusers",
        "view_groupinstitutionusers",
    ],
    "COMMISSION_GENERAL": [
        "view_association_not_public",
        "change_user",
        "view_user",
        "view_associationusers",
        "view_groupinstitutionusers",
    ],
    "COMMISSION_MISC": [
        "view_association_not_public",
        "change_user",
        "view_user",
        "view_associationusers",
        "view_groupinstitutionusers",
    ],
    "STUDENT_INSTITUTION": [
        "change_association",
        "change_user",
        "view_user",
        "change_associationusers",
        "view_associationusers",
        "view_groupinstitutionusers",
    ],
    "STUDENT_MISC": [
        "change_association",
        "change_user",
        "view_user",
        "view_groupinstitutionusers",
    ],
}

