baseURL = 'https://di.pages.unistra.fr/plan_a/plana'
languageCode = 'fr-FR'
defaultContentLanguage = "fr"
title = 'Campulse - Documentation'
theme = 'hugo-theme-relearn'

[params]
  disableLandingPageButton = true
