# Generated by Django 3.2.16 on 2022-12-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MailTemplateVar',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=64, unique=True, verbose_name='Code'),
                ),
                (
                    'description',
                    models.CharField(
                        max_length=128, unique=True, verbose_name='Description'
                    ),
                ),
                (
                    'fake_vars',
                    models.JSONField(blank=True, null=True, verbose_name='Fake vars'),
                ),
            ],
            options={
                'verbose_name': 'Template variable',
                'verbose_name_plural': 'Template variables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=128, unique=True, verbose_name='Code'),
                ),
                (
                    'label',
                    models.CharField(max_length=128, unique=True, verbose_name='Label'),
                ),
                (
                    'description',
                    models.CharField(max_length=512, verbose_name='Description'),
                ),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                (
                    'available_vars',
                    models.ManyToManyField(
                        related_name='mail_templates',
                        to='mail_template.MailTemplateVar',
                        verbose_name='Available variables',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Mail template',
                'verbose_name_plural': 'Mail templates',
                'ordering': ['label'],
            },
        ),
    ]
