# Generated by Django 3.2.16 on 2022-11-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0006_auto_20221114_1459"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityfield",
            options={
                "verbose_name": "Activity field",
                "verbose_name_plural": "Activity fields",
            },
        ),
        migrations.AlterModelOptions(
            name="institution",
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
            },
        ),
        migrations.AlterModelOptions(
            name="institutioncomponent",
            options={
                "verbose_name": "Institution component",
                "verbose_name_plural": "Institution components",
            },
        ),
        migrations.AlterModelOptions(
            name="socialnetwork",
            options={
                "verbose_name": "Social network",
                "verbose_name_plural": "Social networks",
            },
        ),
        migrations.AlterField(
            model_name="activityfield",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="association",
            name="acronym",
            field=models.CharField(default="", max_length=30, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="association",
            name="activities",
            field=models.TextField(default="", verbose_name="Activities"),
        ),
        migrations.AlterField(
            model_name="association",
            name="activity_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="associations.activityfield",
                verbose_name="Activity field",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="address",
            field=models.TextField(default="", verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="association",
            name="approval_date",
            field=models.DateTimeField(null=True, verbose_name="Approval date"),
        ),
        migrations.AlterField(
            model_name="association",
            name="cga_date",
            field=models.DateTimeField(null=True, verbose_name="CGA date"),
        ),
        migrations.AlterField(
            model_name="association",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="association",
            name="email",
            field=models.CharField(default="", max_length=256, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="association",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="associations",
                to="associations.institution",
                verbose_name="Institution",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="institution_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="associations",
                to="associations.institutioncomponent",
                verbose_name="Institution component",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="is_site",
            field=models.BooleanField(default=False, verbose_name="Is site"),
        ),
        migrations.AlterField(
            model_name="association",
            name="last_goa_date",
            field=models.DateTimeField(null=True, verbose_name="Last GOA date"),
        ),
        migrations.AlterField(
            model_name="association",
            name="name",
            field=models.CharField(
                default="", max_length=250, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="path_logo",
            field=models.CharField(
                default="", max_length=250, verbose_name="Logo path"
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="phone",
            field=models.CharField(default="", max_length=25, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="association",
            name="student_count",
            field=models.IntegerField(default=0, verbose_name="Student count"),
        ),
        migrations.AlterField(
            model_name="association",
            name="website",
            field=models.URLField(default="", verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="acronym",
            field=models.CharField(max_length=30, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="institutioncomponent",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="socialnetwork",
            name="location",
            field=models.URLField(verbose_name="Location"),
        ),
    ]
