# Generated by Django 3.2.16 on 2022-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0009_alter_association_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="president_names",
            field=models.CharField(
                default="", max_length=256, verbose_name="President names"
            ),
        ),
    ]
