# Generated by Django 3.2.16 on 2022-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0011_auto_20221212_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
