# Generated by Django 3.2.16 on 2022-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0012_alter_association_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is public'),
        ),
    ]
