# Generated by Django 3.2.16 on 2022-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0013_association_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='path_logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Logo path'),
        ),
    ]
