# Generated by Django 3.2.16 on 2023-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0015_auto_20230109_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
