# Generated by Django 3.2.16 on 2023-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0016_delete_socialnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='social_networks',
            field=models.JSONField(default=list),
        ),
    ]
