# Generated by Django 3.2.16 on 2023-01-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0017_association_social_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='siret',
            field=models.CharField(default='', max_length=14, verbose_name='SIRET'),
        ),
    ]
