# Generated by Django 3.2.16 on 2023-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0018_alter_association_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='phone_pres',
            field=models.CharField(
                default='', max_length=32, verbose_name='President Phone'
            ),
        ),
    ]
