# Generated by Django 3.2.16 on 2023-01-25 09:11

from django.db import migrations, models

import plana.apps.associations.models.association


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0019_association_phone_pres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='path_logo',
            field=models.ImageField(
                blank=True,
                upload_to=plana.apps.associations.models.association.get_logo_path,
                verbose_name='Logo path',
            ),
        ),
    ]
