# Generated by Django 3.2.16 on 2023-01-26 10:02

from django.db import migrations, models

import plana.apps.associations.models.association
import plana.apps.associations.storages


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0020_alter_association_path_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='alt_logo',
            field=models.TextField(default='', verbose_name='Logo description'),
        ),
        migrations.AlterField(
            model_name='association',
            name='path_logo',
            field=plana.apps.associations.storages.DynamicThumbnailImageField(
                blank=True,
                null=True,
                upload_to=plana.apps.associations.models.association.get_logo_path,
                verbose_name='Logo path',
            ),
        ),
    ]
