# Generated by Django 3.2.16 on 2023-01-30 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('associations', '0023_alter_association_alt_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='phone_pres',
            new_name='president_phone',
        ),
        migrations.AlterField(
            model_name='association',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='associations', to='institutions.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='association',
            name='institution_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='associations', to='institutions.institutioncomponent', verbose_name='Institution component'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='InstitutionComponent',
        ),
    ]
