# Generated by Django 3.2.16 on 2023-01-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0024_auto_20230130_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': [('add_association_same_institution', 'Can create an association from the same institution.'), ('add_association_any_institution', 'Can create an association from any institution.'), ('change_association_same_institution', 'Can change most fields of an association from the same institution.'), ('change_association_any_institution', 'Can change fields for an association from any institution.'), ('change_association_any_president', 'Can change fields for an association from any president.'), ('change_association_all_fields', 'Can change institution_id, is_enabled, is_public, is_site for an association.'), ('delete_association_same_institution', 'Can delete an association from the same institution.'), ('delete_association_any_institution', 'Can delete an association from any institution.'), ('view_association_not_enabled', 'Can view a not enabled association.'), ('view_association_not_public', 'Can view a not public association.')], 'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
    ]
