# Generated by Django 3.2.16 on 2023-02-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0026_alter_association_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': [('add_association_any_institution', 'Can create an association from any institution.'), ('change_association_any_institution', 'Can change fields for an association from any institution.'), ('change_association_all_fields', 'Can change institution_id, is_enabled, is_site for an association.'), ('delete_association_any_institution', 'Can delete an association from any institution.'), ('view_association_not_enabled', 'Can view a not enabled association.'), ('view_association_not_public', 'Can view a not public association.')], 'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
    ]
