# Generated by Django 3.2.16 on 2023-03-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0029_auto_20230306_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='can_submit_projects',
            field=models.BooleanField(default=True, verbose_name='Can submit projects'),
        ),
    ]
