# Generated by Django 3.2.16 on 2023-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0030_association_can_submit_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={
                'permissions': [
                    (
                        'add_association_any_institution',
                        'Can create an association from any institution.',
                    ),
                    (
                        'change_association_any_institution',
                        'Can change fields for an association from any institution.',
                    ),
                    (
                        'change_association_all_fields',
                        'Can change restricted fields for an association.',
                    ),
                    (
                        'delete_association_any_institution',
                        'Can delete an association from any institution.',
                    ),
                    (
                        'view_association_not_enabled',
                        'Can view a not enabled association.',
                    ),
                    (
                        'view_association_not_public',
                        'Can view a not public association.',
                    ),
                ],
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
            },
        ),
        migrations.AddField(
            model_name='association',
            name='amount_members_allowed',
            field=models.IntegerField(
                default=4, verbose_name='Amount of members allowed'
            ),
        ),
    ]
