# Generated by Django 3.2.16 on 2023-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('associations', '0032_auto_20230322_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='amount_members_allowed',
            field=models.PositiveIntegerField(
                default=4, verbose_name='Amount of members allowed'
            ),
        ),
        migrations.AlterField(
            model_name='association',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Student count'),
        ),
    ]
