# Generated by Django 3.2.16 on 2023-05-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('associations', '0034_alter_association_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='city',
            field=models.CharField(default='', max_length=128, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='association',
            name='zipcode',
            field=models.CharField(default='', max_length=32, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='association',
            name='email',
            field=models.EmailField(default='', max_length=256, verbose_name='Email'),
        ),
    ]
