# Generated by Django 3.2.16 on 2023-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('associations', '0037_alter_association_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='phone',
            field=models.CharField(default='', max_length=32, verbose_name='Phone'),
        ),
    ]
