# Generated by Django 3.2.16 on 2023-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('associations', '0038_alter_association_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='charter_date',
            field=models.DateField(null=True, verbose_name='Charter date'),
        ),
    ]
