# Generated by Django 3.2.16 on 2023-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('associations', '0039_association_charter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='Email'),
        ),
    ]
