# Generated by Django 3.2.16 on 2023-07-06 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('associations', '0040_alter_association_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='alt_logo',
        ),
    ]
