# Generated by Django 3.2.20 on 2023-08-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('associations', '0041_remove_association_alt_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='president_email',
            field=models.EmailField(
                default='', max_length=256, verbose_name='President email'
            ),
        ),
    ]
