# Generated by Django 4.2.16 on 2025-04-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0043_alter_association_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='association',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approval date'),
        ),
        migrations.AlterField(
            model_name='association',
            name='cga_date',
            field=models.DateField(blank=True, null=True, verbose_name='CGA date'),
        ),
        migrations.AlterField(
            model_name='association',
            name='charter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Charter date'),
        ),
        migrations.AlterField(
            model_name='association',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='association',
            name='country',
            field=models.CharField(blank=True, max_length=128, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='association',
            name='current_projects',
            field=models.TextField(blank=True, verbose_name='Current projects'),
        ),
        migrations.AlterField(
            model_name='association',
            name='last_goa_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last GOA date'),
        ),
        migrations.AlterField(
            model_name='association',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='association',
            name='president_email',
            field=models.EmailField(blank=True, max_length=256, verbose_name='President email'),
        ),
        migrations.AlterField(
            model_name='association',
            name='president_names',
            field=models.CharField(blank=True, max_length=256, verbose_name='President names'),
        ),
        migrations.AlterField(
            model_name='association',
            name='president_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='President phone'),
        ),
        migrations.AlterField(
            model_name='association',
            name='siret',
            field=models.CharField(blank=True, max_length=14, verbose_name='SIRET'),
        ),
        migrations.AlterField(
            model_name='association',
            name='social_networks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='association',
            name='social_object',
            field=models.TextField(blank=True, verbose_name='Social object'),
        ),
        migrations.AlterField(
            model_name='association',
            name='zipcode',
            field=models.CharField(blank=True, max_length=32, verbose_name='Zipcode'),
        ),
    ]
