# Generated by Django 4.2.16 on 2025-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0044_alter_association_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
