# Generated by Django 4.2.19 on 2026-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0045_alter_association_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='charter_status',
            field=models.CharField(
                choices=[
                    ('CHARTER_DRAFT', 'Charter Draft'),
                    ('CHARTER_DRAFT_PROCESSED', 'Charter Draft Processed'),
                    ('CHARTER_REJECTED', 'Charter Rejected'),
                    ('CHARTER_PROCESSING', 'Charter Processing'),
                    ('CHARTER_VALIDATED', 'Charter Validated'),
                    ('CHARTER_EXPIRED', 'Charter Expired'),
                ],
                default='CHARTER_DRAFT',
                max_length=32,
                verbose_name='Charter status',
            ),
        ),
    ]
