# Generated by Django 3.2.19 on 2023-05-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0049_alter_user_phone'),
        ('institutions', '0003_remove_institution_email'),
        ('documents', '0016_auto_20230503_0936'),
        ('commissions', '0002_commission_is_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commission',
            new_name='Fund',
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'Fund', 'verbose_name_plural': 'Funds'},
        ),
        migrations.AlterField(
            model_name='commissiondate',
            name='commission',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to='commissions.fund',
                verbose_name='Fund',
            ),
        ),
    ]
