# Generated by Django 3.2.19 on 2023-06-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0004_rename_commissiondate_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionFund',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'commission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='commissions.commission',
                        verbose_name='Commission',
                    ),
                ),
                (
                    'fund',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='commissions.fund',
                        verbose_name='Fund',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Commission Fund',
                'verbose_name_plural': 'Commissions Funds',
            },
        ),
    ]
