# Generated by Django 3.2.19 on 2023-06-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0005_commissionfund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
            },
        ),
        migrations.RemoveField(
            model_name='commission',
            name='commission',
        ),
        migrations.AddField(
            model_name='commission',
            name='is_open_to_projects',
            field=models.BooleanField(
                default=False, verbose_name='Is open to projects'
            ),
        ),
    ]
