# Generated by Django 3.2.19 on 2023-06-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0006_auto_20230605_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionfund',
            name='commission',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='commissions.commission',
                verbose_name='Commission',
            ),
        ),
    ]
