# Generated by Django 3.2.19 on 2023-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commissions', '0007_alter_commissionfund_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='name',
            field=models.CharField(
                default='', max_length=250, unique=True, verbose_name='Name'
            ),
        ),
    ]
