# Generated by Django 4.2.16 on 2025-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_fund_attribution_template_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='attribution_template_path',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Attribution template path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='decision_attribution_template_path',
            field=models.CharField(
                blank=True, default='', max_length=250, verbose_name='Decision attribution template path'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='postpone_template_path',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Postpone template path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='rejection_template_path',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Rejection template path'),
            preserve_default=False,
        ),
    ]
