# Generated by Django 4.2.16 on 2025-11-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_alter_fund_attribution_template_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
